defaults:
  - _self_
  - task@_global_: knot
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
_maybe_slurm: ${oc.env:SLURM_JOB_ID,local}
use_wandb: true
wandb:
  enabled: ${use_wandb}
  project: knots-dev-drqv2
  entity: zc478
  name: ${_maybe_slurm}
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50

task_kwargs: ???

agent:
  _target_: drqv2.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3

# python train.py -m hydra/launcher=submitit_slurm ++hydra.launcher.srun_args="['--cpu-bind=none']"
hydra:
  run:
    dir: ./exp_local/${_maybe_slurm}_${now:%Y-%m-%d-%H-%M-%S-%f}_${hydra.job.override_dirname}
  sweeper:
    params:
      task_name: knot_unknot,knot_tie_unknot,knot_eq1
      task_kwargs.task_max_n_crossings: 2,3,4
  sweep:
    dir: ./exp/${_maybe_slurm}_${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 2880
    # srun_args: ["--cpu-bind=none"] # TODO: move from cli to file
    cpus_per_task: 4 # 10
    gpus_per_node: 1
    partition: lil-gpuhi
    tasks_per_node: 1
    mem_gb: 32 # 160
    nodes: 1
    # submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
    submitit_folder: ./exp/${_maybe_slurm}_${now:%Y-%m-%d-%H-%M-%S}_submitit/.slurm
    additional_parameters:
      wckey: ''
